<a href="https://colab.research.google.com/github/MikhailGalperin/MyFirstRep/blob/main/Homework__03dec2020__Part_1_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://colab.research.google.com/drive/1IKjFH-OYifkjY0g3U6h5hLjd6IpYluFU

# Новый раздел

## Домашнее задание. Часть 1.

- напишем свою собственную библиотеку

Вего за эту часть ДЗ можно набрать максимум **11.5 баллов**. Разбиение баллов по каждой из задач представлено непосредственно перед текстом каждой задачи.

**Дедлайн - пятница, 11.12.2020 в 23:59.**

Дедлайн жесткий, сдача после дедлайна - 0 баллов за ДЗ.

Ссылка на ноутбук в колабе: https://colab.research.google.com/drive/1LgWtESFmiNW1WlVFCHKyNl_BxAWxoL3Z?usp=sharing

Допустим мы хотим написать фнкцию, которая складывает 2 числа и сохранить ее в отдельный .py файл. Пример:

In [ ]:
%%writefile lib.py
def summ(a1, b1):
    return a1+b1

Writing lib.py


In [ ]:
from lib import summ

In [ ]:
summ(2,6)

NameError: ignored

Попробуем запустить через "терминал"

In [ ]:
!python3 lib.py

Ничего не происходит. А теперь добавим `if __name__ == "__main__"` в наш код и пересохраним файл lib.py

In [ ]:
%%writefile lib.py
import sys

a1 = float( sys.argv[1] ) # Считываем аргументы прямо из терминала
b1 = float( sys.argv[2] ) # Считываем аргументы прямо из терминала

def summ(a1, b1):
    return a1+b1

if __name__ == "__main__":
    print(summ(a1, b1))


ValueError: ignored

In [ ]:
!python3 lib.py 2 4

6.0


# **Задание 1**

Реализуйте следующие функции и сохраните их в библиотеку **my_math_lib.py** (пока без использования конструкции `if __name__ == "__main__"`)

**1 point** 
1. **def deg_to_rad()**. Напишите программу на Python для преобразования градусов в радианы.  *(Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса)* **1 point**

**1 point** 
2. **def rad_to_def()**. Напишите программу Python для преобразования радианов в градусы.

**1.5 point** 
3. **def discriminant()**. Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

**1.5 point** 
4. **def power_base_sum()**. Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.

Пример: power_base_sum(2, 100)

Выход: 115



**2 point** 
5. **def magic_square()**. Напишите программу на Python для вычисления [магического квадрата](https://ru.wikipedia.org/wiki/Магический_квадрат)

Note:

Магический, или волшебный квадрат — это квадратная таблица , заполненная числами таким образом, что сумма чисел в каждой строке, каждом столбце и на обеих диагоналях одинакова. Сумма чисел в каждой строке, столбце и на диагоналях, называется магической константой, M.

**1 point** 
6. **def mult_list()**. Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)

**1 point** 
7. **def create_list()**. Напишите функцию Python для создания и вывода списка (при помощи print()), в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).

In [ ]:
%%writefile my_math_lib.py

#ПЕРЕВОД ГРАДУСОВ В РАДИАНЫ
import math
deg = 45

def deg_to_rad(deg):
  return deg * math.pi / 180

if __name__ == "__main__":
  rad = deg_to_rad(deg)
  print('1.1 перевод', deg, 'градусов в радианы: ', rad)

  #проверка
  print('проверка', math.radians(deg))

# ПЕРЕВОД РАДИАН В ГРАДУСЫ
import math
rad = 0.5

def rad_to_deg (rad):
  return rad * 180 / math.pi

if __name__ == "__main__":
  deg = rad_to_deg(rad)
  print('1.2 перевод', rad, 'радиан в градусы: ', deg)

  #проверка
  print('проверка', math.degrees(rad))

#ВЫЧИСЛЕНИЕ ДИСКРИМИНАНТА КВАДРАТНОГО УРАВНЕНИЯ
x = 1
y = 2
z = 3
def discriminant (a, b, c):
  return b ** 2 - 4 * a * c

if __name__ == "__main__":
  d = discriminant(x, y, z)
  print ('1.3 дискриминант равен', d)

#ВЫЧИСЛЕНИЕ СУММЫ ЦИФР ОСНОВАНИЯ В СТЕПЕНИ
pbs1 = 2
pbs2 = 100
pbs3 = 0
def power_base_sum (a, b):
  c = a ** b
  d = 0
  e = 0
  while c > 0:
    d = c % 10
    e = e + d
    c = c // 10
  return e

if __name__ == "__main__":
  pbs3 = power_base_sum(pbs1, pbs2)
  print ('1.4 сумма цифр основания в степени равна', pbs3)

#ПОСТРОЕНИЕ МАГИЧЕСКОГО КВАДРАТА

import numpy as np
size = 10

def magic_square(a):
  b = np.arange(1, a + 1)
  
  if a < 3:
    print('магический квадрат со стороной', a, 'невозможен')
  
  if a % 2 != 0:
    square = a * np.mod(b[:, None] + b - (a + 3) // 2, a) + np.mod(b[:, None] + 2 * b - 2, a) + 1
  
  elif a % 4 == 0:
    c = np.mod(b, 4) // 2
    d = c[:, None] == c
    square = np.arange(1, a * a + 1, a)[:, None] + np.arange(a)
    square[d] = a * a + 1 - square[d]
  
  else:
    c = (a - 2) // 4
    d = np.concatenate((np.arange(c), np.arange(a - c + 1, a)))
    half_a = a // 2
    half_a_basis = np.arange(half_a)
    square = magic_square(half_a)
    square = np.block([[square, square + half_a ** 2 * 2], [square + half_a ** 2 * 3, square + half_a ** 2]])
    
    square[np.ix_(np.concatenate((half_a_basis, half_a_basis + half_a)), d)] = square[np.ix_(np.concatenate((half_a_basis + half_a, half_a_basis)), d)]
    square[np.ix_([c, c + half_a], [0, c])] = square[np.ix_([c + half_a, c], [0, c])]
  
  return square

if __name__ == "__main__":    
  print ('1.5 магический квадрат со стороной', size)
  print(magic_square(size))

#УМНОЖЕНИЕ ЧИСЕЛ В МАССИВЕ

import numpy as np
multiplist = [1, 2, 3, 4, 5, 6]

def mult_list(a):
  mult = 1
  for i in a:
    mult = mult * i
  return mult

if __name__ == "__main__":
  print('1.6 произведение чисел в массиве', multiplist, 'равно', mult_list(multiplist))
  print('проверка', np.prod(multiplist))

#СПИСОК КВАДРАТОВ
a = 1
b = 30

def create_list (x, y):
  squares = [i ** 2 for i in range(x, y + 1)]
  print (squares)
  return squares

if __name__ == "__main__":
  print('1.7 список квадратов чисел от', a, 'до', b)
  c = create_list(a, b)

Overwriting my_math_lib.py


In [ ]:
#TODO

# **Задание 2**
Импортируйте все методы из модуля my_math_lib.

 **0.25 point** 
 - при помощи функции **def discriminant()** посчитайте дискриминант следующего уравнения: 
 $x^{2}+3 x+4=0$

**0.25 point** 
 - постройте магический квадрат размера 5х5

In [ ]:
from my_math_lib import *

print('дискриминант уравнения x ** 2 + 3 * x + 4 = 0 равен', discriminant (1, 3, 4))
print('магический квадрат со стороной 5')
print(magic_square(5))

дискриминант уравнения x ** 2 + 3 * x + 4 = 0 равен -7
магический квадрат со стороной 5
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]


# **Задание 3**

**2 point**
* Добавьте в вашу библиотеку конструкцию `if __name__ == "__main__"`, которая должна принимать одну из вышеперечисленных функций. 
* Важно! аргументы, подаваемые в функцию, должны подаваться напряму через терминал (как в примере)! Используйте для этого библиотеку `sys`

In [ ]:
%%writefile my_math_lib_task3.py
#ВЫЧИСЛЕНИЕ ДИСКРИМИНАНТА КВАДРАТНОГО УРАВНЕНИЯ
import sys
x = float( sys.argv[1] )
y = float( sys.argv[2] )
z = float( sys.argv[3] )
def discriminant_task3 (a, b, c):
  return b ** 2 - 4 * a * c

if __name__ == "__main__":
  d = discriminant_task3(x, y, z)
  print ('дискриминант равен', d)

Overwriting my_math_lib_task3.py


In [ ]:
#TODO

In [ ]:
!python3 my_math_lib_task3.py 1 3 4

дискриминант равен -7.0
