<a href="https://colab.research.google.com/github/MikhailGalperin/MyFirstRep/blob/main/Homework__15dec2020_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание к 7 уроку.

**Дедлайн: 23.12.2020**

colab: https://colab.research.google.com/drive/1KLD5pDCa0ka_g1U4D2ExihaaEwXzfTPW?usp=sharing

**ФОРМАТ ОТЧЕТНОСТИ:** pdf-файл с решенными задачами (задачи 2-9), ноутбук с проверкой решения этих задач (при помощи numpy), и pdf файл с отчетом по 1-ой задаче (краткий пересказ статьи). Вы можете оформить решения с использованием Markdown (писать текст прямо в юпитер ноутбуке), Latex, Word или же решить в тетради и сформировать pdf из фото.

Итого: 2 pdf файла.

Все задания необходимо выполнять ВРУЧНУЮ. А также проверить корректность полученных результатов с использованием Numpy.

Туториал как писать "Latex-формулы" прямо в Юпитере:
https://www.youtube.com/watch?v=vSc25kdgecg

Ноутбук с примером формул: https://nbviewer.jupyter.org/github/postlogist/course_opt/blob/master/jupyter_tutorial/02_markdown.ipynb


## Пример


Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [ ]:
# Проверка

import numpy as np
a = [1, 2, 3, 4, 5]
b = [2, 5, 8, 11, 14]
c = [3, 9, 14, 20, 26]
d = [5, 14, 22, 31, 40]

x = np.array([a, b, c, d])
r = np.linalg.matrix_rank(x)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


# Задачи

**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.


__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

# Доп материалы
1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)

In [ ]:
# Проверка

# 2. Сумма и произведение матриц.

import numpy as np
a1 = [1, -2]
a2 = [3, 0]
b1 = [4, -1]
b2 = [0, 5]
a = np.array([a1, a2])
b = np.array([b1, b2])
c = a + b
d = np.dot(a, b)
print('сумма матриц')
print(c)
print('произведение матриц')
print(d)

сумма матриц
[[ 5 -3]
 [ 3  5]]
произведение матриц
[[  4 -11]
 [ 12  -3]]


In [ ]:
# 3. Линейная комбинация

import numpy as np
a1 = [1, 7]
a2 = [3, -6]
b1 = [0, 5]
b2 = [2, -1]
c1 = [2, -4]
c2 = [1, 1]
a = np.array([a1, a2])
b = np.array([b1, b2])
c = np.array([c1, c2])

d = 3 * a - 2 * b + 4 * c
print('линейная комбинация')
print(d)


линейная комбинация
[[ 11  -5]
 [  9 -12]]


In [18]:
# 4. Транспонирование и произведение матриц

import numpy as np
a1 = [4, 1]
a2 = [5, -2]
a3 = [2, 3]
a = np.array([a1, a2, a3])
b = a.transpose()
c = np.dot(a, b)
d = np.dot(b, a)
print('произведение A * AT')
print(c)
print('произведение AТ * A')
print(d)

произведение A * AT
[[17 18 11]
 [18 29  4]
 [11  4 13]]
произведение AТ * A
[[45  0]
 [ 0 14]]


In [71]:
# 5. Перемножение двух произвольных матриц

import random

def formation (rows, columns):
  matrix_temp = []
  matrix = []
  for i in range(0, rows):
    for j in range(0, columns):
      matrix_temp.append(random.randint(1, 10))
    matrix.append(matrix_temp)
    matrix_temp = []
  return matrix

rows_1 = random.randint(1, 5)
columns_1 = random.randint(1, 5)
#rows_2 = random.randint(1, 5)
# очень редко выпадают равные количества столбцов в первой матрице и строк во второй; для удобства проверки делаем их равными
rows_2 = columns_1
columns_2 = random.randint(1, 5)

matrix_1 = formation (rows_1, columns_1)
matrix_2 = formation (rows_2, columns_2)

def multiplication (matrix_1, matrix_2):
  elem = 0
  matrix_temp = []
  matrix_3 = []
  
  rows_1 = len(matrix_1)
  columns_1 = len(matrix_1[0])
  rows_2 = len(matrix_2)
  columns_2 = len(matrix_2[0])
  
  if rows_2 != columns_1:
    print('умножение матриц невозможно вследствие несовпадения размеров')
  else:
    for i in range(0, rows_1):
      for j in range(0, columns_2):
        for k in range(0, columns_1):
          elem = elem + matrix_1[i][k] * matrix_2[k][j]
        matrix_temp.append(elem)
        elem = 0
      matrix_3.append(matrix_temp)
      matrix_temp = []
  return matrix_3

matrix_3 = multiplication (matrix_1, matrix_2)

if rows_2 == columns_1:
  print('первая матрица')
  print(matrix_1)
  print('вторая матрица')
  print(matrix_2)
  print('результирующая матрица')
  print(matrix_3)
  print('P.S.: как записать матрицу в привычном виде, не используя Numpy, так и не придумал')
else:
  print('умножение не было выполнено')

первая матрица
[[2, 6, 4, 8], [5, 3, 8, 2], [2, 4, 5, 6], [6, 2, 7, 2]]
вторая матрица
[[4, 6, 7, 8], [7, 9, 2, 2], [4, 1, 1, 2], [6, 8, 6, 5]]
результирующая матрица
[[114, 134, 78, 76], [85, 81, 61, 72], [92, 101, 63, 64], [78, 77, 65, 76]]
P.S.: как записать матрицу в привычном виде, не используя Numpy, так и не придумал


In [ ]:
# 6. Определители матриц

import numpy as np
import math
import random

x = random.random()
a1 = [math.sin(x), (-1) * math.cos(x)]
a2 = [math.cos(x), math.sin(x)]
a = np.array([a1, a2])

b1 = [8, 4, 6]
b2 = [0, 5, 1]
b3 = [0, 0, 9]
b = np.array([b1, b2, b3])

c1 = [2, 3, 4]
c2 = [5, 6, 7]
c3 = [8, 9, 10]
c = np.array([c1, c2, c3])

print('определитель матрицы 1')
print(np.linalg.det(a))
print('определитель матрицы 2')
print(np.linalg.det(b))
print('определитель матрицы 3')
print(np.linalg.det(c))

определитель матрицы 1
0.9999999999999999
определитель матрицы 2
360.00000000000006
определитель матрицы 3
0.0


In [ ]:
# 7. Определители матриц

# здесь я пытаюсь показать, что:
# а) детерминант квадрата матрицы равен квадрату детерминанта исходной матрицы
# б) детерминант транспонированной матрицы равен детерминанту исходной матрицы
# в) детерминант матрицы, умноженной на два, равен детерминанту исходной матрицы, умноженному на два в степени порядка матрицы
# по условиям задачи детерминант исходной матрицы равен 4; следовательно детерминанты равны соответственно 16; 4; 4 * 2 ** n

import numpy as np
import random

a11 = random.random()
a12 = random.random()
a21 = random.random()
a22 = random.random()
a1 = [a11, a12]
a2 = [a21, a22]
a = np.array([a1, a2])
det_a = np.linalg.det(a)

# детерминант А ** 2
b = np.dot(a, a)
det_b = np.linalg.det(b)
print('детерминант матрицы А', det_a)
print('детерминант матрицы А в квадрате', det_a ** 2)
print('детерминант квадрата матрицы А', det_b)
print()

# детерминант АТ
с = a.transpose()
det_с = np.linalg.det(с)
print('детерминант матрицы А', det_a)
print('детерминант транспонированной матрицы А', det_с)
print()

# детерминант 2 * А
d = 2 * a
det_d = np.linalg.det(d)
print('детерминант матрицы А', det_a)
print('детерминант матрицы А * 2 в степени 2 (порядок матрицы)', det_a * 2 * 2)
print('детерминант матрицы 2 * А', det_d)
print()

детерминант матрицы А 0.2555885010918327
детерминант матрицы А в квадрате 0.06532548189036975
детерминант квадрата матрицы А 0.0653254818903698

детерминант матрицы А 0.2555885010918327
детерминант транспонированной матрицы А 0.25558850109183273

детерминант матрицы А 0.2555885010918327
детерминант матрицы А * 2 в степени 2 (порядок матрицы) 1.0223540043673307
детерминант матрицы 2 * А 1.0223540043673307



In [ ]:
# 8. Вырожденная матрица

import numpy as np

a1 = [-2, 7, -3]
a2 = [4, -14, 6]
a3 = [-3, 7, 13]
a = np.array([a1, a2, a3])

print('определитель матрицы равен')
print(np.linalg.det(a))
print('следовательно, матрица вырожденная')


определитель матрицы равен
0.0
следовательно, матрица вырожденная


In [ ]:
# 9. Ранг матрицы

import numpy as np

a1 = [1, 2, 3]
a2 = [1, 1, 1]
a3 = [2, 3, 4]
a = np.array([a1, a2, a3])
rank_a = np.linalg.matrix_rank(a)
print('ранг матрицы равен', rank_a)

b1 = [0, 0, 2, 1]
b2 = [0, 0, 2, 2]
b3 = [0, 0, 4, 3]
b4 = [2, 3, 5, 6]
b = np.array([b1, b2, b3, b4])
rank_b = np.linalg.matrix_rank(b)
print('ранг матрицы равен', rank_b)

ранг матрицы равен 2
ранг матрицы равен 3
